format = """
$directory\
[ ](fg:#0d1a26 bg:#0d1a26)\
$git_branch\
$git_status\
[ ](fg:#0d1a26)\
\n$character
"""

right_format = """
$cmd_duration\
$username\
$time
"""

# コマンドラインに1行分のスペースを入れる
add_newline = true

[username]
style_user = "fg:#00e5ff bold"
style_root = "fg:#ff2d6f bold"
format = "[$user]($style) "
disabled = false

[fill]
symbol = ' '

[directory]
style = "fg:#050510 bg:#00e5ff bold"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
read_only = ' 󰌾 '
read_only_style = 'fg:#ff2d6f bg:#0d1a26'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:#0d1a26"
format = '[[ $symbol $branch ](fg:#00e5ff bg:#0d1a26)]($style)'

[git_status]
style = "bg:#0d1a26"
format = '[[($all_status$ahead_behind )](fg:#00b4cc bg:#0d1a26)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:#00e5ff'
format = "[ $duration]($style) "

[time]
disabled = false
time_format = "%R"
format = '[[   $time ](fg:#006b7d)]($style)'

[character]
success_symbol = '[❯](bold fg:#00e5ff)'
error_symbol = '[❯](bold fg:#ff2d6f)'
vimcmd_symbol = '[V](bold fg:#00e5ff) '
